#!/bin/tcsh -f
#
# AUTHOR:
# Rostam Golesorkhtabar
# r.golesorkhtabar@gmail.com
#
# DATE:
# Tue Jan 1  00:00:00  2013
#
# SYNTAX:
# OPTIMIZE_Clean_WIEN2k 
#
# EXPLANATION:
#
#
set Dir_path = $cwd
set dir_list = `ls -d *_??`
foreach dir_num ($dir_list)
    cd $dir_num
    save_lapw {$dir_num}_Converged
    clean_lapw -s
    mkdir tmpdir
    cd tmpdir
    cp -f ../{$dir_num}_Converged* .
    cp -f ../{$dir_num}.dayfile .
    cp -f ../{$dir_num}.in0 .
    cp -f ../{$dir_num}.in1 .
    cp -f ../{$dir_num}.in2 .
    cp -f ../{$dir_num}.inm .
    cp -f ../{$dir_num}.klist .
    cd ..
    rm -f *
    rm .l*
    rm .m*
    rm .s*
    rm .t*
    rm .p*
    mv -f tmpdir/* .
    rm -r tmpdir
    cd ..
end
exit
